version: '3'
services:
  postgresql11:
    image: postgres:11
    container_name: postgresql11
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - C:\Users\User\docker\pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.pl
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5444:80"
  app:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/app
    expose:
      - "8080"
    depends_on:
      - postgresql11
volumes:
  postgres:
  pgadmin4:
    driver: local