CREATE TABLE USERS(
    USER_ID BIGINT PRIMARY KEY,
	USER_NAME varchar(250) NOT NULL,
	USER_EMAIL varchar(50) NOT NULL,
	PASSWORD VARCHAR(255),
    ACCOUNT_EXPIRED BOOLEAN,
    ACCOUNT_LOCKED BOOLEAN,
    CREDENTIALS_EXPIRED BOOLEAN,
    ENABLED BOOLEAN
);