CREATE TABLE JOIN_USERS_GROUPS(
USER_ID BIGINT NOT NULL,
GROUP_ID BIGINT NOT NULL,
PRIMARY KEY(USER_ID, GROUP_ID),
FOREIGN KEY (USER_ID) references USERS(USER_ID),
FOREIGN KEY (GROUP_ID) references GROUPS(GROUP_ID)
)