INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('read-client', 'groups-api', '$2a$08$KMAMWy7cb2P25qXRrdoDgeDfKf43YnCMbu2KGc54ScidjAAF734K2',
	'read', 'password,authorization_code,refresh_token,implicit', 'USERS', 10800, 2592000);

INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('read-write-client', 'groups-api', '$2a$08$F3QeAdz1kzMJf8KJzf4.euEKCwPRaJGkpCGiLjva31NsZT39JwjDm',
	'read,write', 'password,authorization_code,refresh_token,implicit', 'USERS', 10800, 2592000);